CREATE TABLE [dbo].[tblAnexo29] (
    [FolioTexto]       VARCHAR (50)    NOT NULL,
    [Year]             INT             NOT NULL,
    [Folio]            INT             NOT NULL,
    [FolioTipo]        NCHAR (10)      NOT NULL,
    [Fecha]            DATETIME        NULL,
    [Descripcion]      VARCHAR (MAX)   NULL,
    [PesoNeto]         DECIMAL (18, 3) NULL,
    [Regimen]          NCHAR (10)      NULL,
    [Pedimento]        VARCHAR (50)    NULL,
    [Motivo]           VARCHAR (MAX)   NULL,
    [NoContenedor]     VARCHAR (50)    NULL,
    [Medida]           VARCHAR (50)    NULL,
    [Tipo]             VARCHAR (50)    NULL,
    [Sellos]           VARCHAR (50)    NULL,
    [PesoBruto]        INT             NULL,
    [NombreExp]        VARCHAR (100)   NULL,
    [Direccion]        VARCHAR (100)   NULL,
    [Ciudad]           VARCHAR (50)    NULL,
    [RFC]              VARCHAR (50)    NULL,
    [NombreTransporte] VARCHAR (100)   NULL,
    [Placas]           VARCHAR (50)    NULL,
    [NoEconomico]      VARCHAR (50)    NULL,
    [CAAT]             VARCHAR (50)    NULL,
    [NombreOperador]   VARCHAR (100)   NULL,
    [NoLicencia]       VARCHAR (50)    NULL,
    [NombreAgente]     VARCHAR (100)   NULL,
    [Patente]          NCHAR (10)      NULL,
    [Username]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_tblAnexo29] PRIMARY KEY CLUSTERED ([FolioTexto] ASC, [Year] ASC) WITH (FILLFACTOR = 90)
);

